---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What would you like to name your Tenant?"
      private: no

  tasks:
    - name: ENSURE TENANT VRF EXISTS
      aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "VRF Created Using Ansible"
        
  tasks:
    - name: CREATE BRIDGE DOMAIN SUBNET B2CC_ENTARCH_APP_BD
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "PROD_TN"
        bd: "B2CC_ENTARCH_APP_BD"
        vrf: "OPC_VRF"
        arp_flooding: yes
        description: "INFRNET-4191 Openstack"

    - name: Create SUBNET for B2CC_ENTARCH_APP_BD
      aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "PROD_TN"
        bd: "B2CC_ENTARCH_APP_BD"
        gateway: "10.51.68.254"
        mask: 24
        description: "INFRNET-4191 Openstack"
        
    - name: CREATE BRIDGE DOMAIN SUBNET B2CC_ENTARCH_NFS_BD
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "PROD_TN"
        bd: "B2CC_ENTARCH_NFS_BD"
        vrf: "OPC_VRF"
        arp_flooding: yes
        description: "INFRNET-4191 Openstack"
        
    - name: Create SUBNET for B2CC_ENTARCH_NFS_BD
       aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "PROD_TN"
        bd: "B2CC_ENTARCH_NFS_BD"
        gateway: "10.51.168.254"
        mask: 24
        description: "INFRNET-4191 Openstack"
