---
- name: CREATE NEW OpenStack BD EPG NETWORK CONFIGURATION
  hosts: apic
  connection: local
  gather_facts: false
  vars_prompt:
    - name: password
      prompt: Type your APIC Password.
      private: yes
    - name: tenant
      prompt: Which Tenant you want this change?
      private: no
  tasks:
    - name: Creating Bridge Domain BD1 "{{ bd1 }}"
      cisco.aci.aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        bd: "{{ bd1 }}"
        vrf: "{{ vrf }}"
        arp_flooding: true
        bd_type: ethernet
        enable_routing: true
        l2_unknown_unicast: proxy 
        l3_unknown_multicast: flood
        ipv6_l3_unknown_multicast: flood
        multi_dest: bd-flood
        description: "{{ ticket }}" "{{ description }}"
    - name: Creating Bridge Domain BD2 "{{ bd2 }}".
      cisco.aci.aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        bd: "{{ bd2 }}"
        vrf: "{{ vrf }}"
        arp_flooding: true
        bd_type: ethernet
        enable_routing: true
        l2_unknown_unicast: proxy 
        l3_unknown_multicast: flood
        ipv6_l3_unknown_multicast: flood
        multi_dest: bd-flood
    - name: Creating BD1 SUBNET/24
      cisco.aci.aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        bd: "{{ bd1 }}"
        gateway: "{{ gw1 }}"
        mask: 24
        description: INFRNET-4191 Openstack
    - name: Creating BD2 SUBNET/24
      cisco.aci.aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        bd: "{{ bd2 }}"
        gateway: "{{ gw2 }}"
        mask: 24
    - name: Associate EPG1 with AEP1
      cisco.aci.aci_aep_to_epg:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        aep: "{{ aep1 }}"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ epg1 }}"
        vlan: "{{ vlan1 }}"
        interface_mode: trunk
    - name: Associate EPG2 with AEP2
      cisco.aci.aci_aep_to_epg:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        aep: "{{ aep2 }}"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ epg2 }}"
        vlan: "{{ vlan2 }}"
        interface_mode: trunk
        state: present
