---
- name: CREATE PRE-REQUISITE CONFIGURATION
  hosts: apic
  connection: local
  gather_facts: false
  vars_prompt:
    - name: tenant
      prompt: Which Tenant you want this change?
      private: no
    - name: password
      prompt: Type you APIC Password:
  tasks:
    - name: Ensure API key is present in configuration1 file
      ansible.builtin.lineinfile:
        path: /home/MyAnsibleCode/secret/configuration1.ini
        line: "APIC_Password={{ password }}"
    - name: ENSURE APPLICATIONS TENANT EXISTS
      cisco.aci.aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        description: Tenant Created Using Ansible
    - name: ENSURE TENANT VRF EXISTS
      cisco.aci.aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        validate_certs: false
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"
        description: VRF Created Using Ansible
    - name: Add a new VLAN pool
      cisco.aci.aci_vlan_pool:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        pool: SERVER_VLP
        pool_allocation_mode: static
        description: SERVER_VLP
        state: present
    - name: Add a new VLAN pool range
      cisco.aci.aci_encap_pool_range:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        pool: SERVER_VLP
        pool_type: vlan
        pool_allocation_mode: static
        range_name: SERVER_VLP
        range_start: 1000
        range_end: 1999
        allocation_mode: inherit
        state: present
    - name: Add a new physical domain
      cisco.aci.aci_domain:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        domain: SERVER_PD
        domain_type: phys
        state: present
    - name: Add domain to VLAN pool binding
      cisco.aci.aci_domain_to_encap_pool:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        domain: SERVER_PD
        domain_type: phys
        pool: SERVER_VLP
        pool_type: vlan
        pool_allocation_mode: static
        state: present
    - name: Add a new AP
      cisco.aci.aci_ap:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        description: default ap
        monitoring_policy: default
        state: present
    - name: Add a new App AEP
      cisco.aci.aci_aep:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        aep: "{{ aep1 }}"
        description: default
        infra_vlan: true
        state: present
    - name: Add a new NFS AEP
      cisco.aci.aci_aep:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        aep: "{{ aep2 }}"
        description: default
        infra_vlan: true
        state: present
